function execute() {
    return new Promise((resolve, reject) => {
        console.log('A promise estÃ¡ sendo executada.')
        setTimeout(() => {
            console.log('Resolvendo a promise...')
            resolve('Resultado')
        }, 3 * 1000)
    })
}

const p = execute()

// console.log(p)

// setTimeout(() => {
//     console.log(p)
// }, 5 * 1000)

// ...

execute().then((result) => {
    console.log(`A promise foi resolvida. O resultado foi: ${result}`)
}).catch((err) => {
    console.log(`A promise foi rejeitada! Motivo: ${err}`)
}).finally(() => {
    console.log('A promsie foi finalizada.')
})